import colors from './colors';
import boxes from './boxes';
import { ProjectReport, UseCase, Recommendation } from '../lib/project-analyzer';

/**
 * Beautiful formatting for project analysis reports
 */
export class ReportFormatter {
  /**
   * Format the complete project analysis report
   */
  static formatReport(report: ProjectReport): string {
    const sections = [
      this.formatHeader(report.basicInfo),
      this.formatProjectOverview(report),
      this.formatUseCases(report.useCases),
      this.formatTechStack(report.techStack),
      this.formatComplexity(report.complexity),
      this.formatRecommendations(report.recommendations),
      this.formatFooter(),
    ];

    return sections.join('\n');
  }

  /**
   * Format report header with project basics
   */
  private static formatHeader(basicInfo: any): string {
    const header = `
${colors.heading('📊 Project Analysis Report')}
${colors.dim('Generated by PromptBrain CLI')}

${colors.primary('Project:')} ${colors.highlight(basicInfo.name)}
${colors.primary('Version:')} ${colors.neutral(basicInfo.version)}
${colors.primary('Description:')} ${colors.dim(basicInfo.description)}
`;

    return header;
  }

  /**
   * Format project overview section
   */
  private static formatProjectOverview(report: ProjectReport): string {
    const { basicInfo, purpose, architecture } = report;
    
    const overview = `
${colors.heading('🎯 Project Overview')}

${colors.primary('Domain:')} ${colors.highlight(purpose.domain)}
${colors.primary('Category:')} ${colors.highlight(purpose.category)}
${colors.primary('Project Age:')} ${colors.neutral(basicInfo.age)}
${colors.primary('Code Size:')} ${colors.neutral(`${basicInfo.linesOfCode.toLocaleString()} lines across ${basicInfo.fileCount} files`)}

${colors.primary('Key Features:')}
${purpose.features.map(feature => `  • ${colors.success(feature)}`).join('\n')}

${colors.primary('Architecture Patterns:')}
${architecture.patterns.map(pattern => `  • ${colors.primary(pattern)}`).join('\n')}
`;

    return overview;
  }

  /**
   * Format use cases section
   */
  private static formatUseCases(useCases: UseCase[]): string {
    if (useCases.length === 0) {
      return `\n${colors.heading('💼 Use Cases')}\n${colors.dim('No specific use cases detected')}`;
    }

    let section = `\n${colors.heading('💼 Primary Use Cases')}\n`;

    useCases.forEach((useCase, index) => {
      const useCaseBox = `
${colors.primary(`${index + 1}. ${useCase.title}`)}
${colors.dim(useCase.description)}

${colors.primary('Actors:')} ${useCase.actors.map(actor => colors.highlight(actor)).join(', ')}

${colors.primary('Typical Flow:')}
${useCase.flow.map((step, i) => `  ${colors.dim(`${i + 1}.`)} ${step}`).join('\n')}
`;

      section += boxes.box(useCaseBox.trim(), {
        borderColor: colors.primary,
        padding: 1,
      }) + '\n';
    });

    return section;
  }

  /**
   * Format technology stack section
   */
  private static formatTechStack(techStack: any): string {
    const sections = [];

    if (techStack.frontend.length > 0) {
      sections.push(`${colors.primary('Frontend:')} ${techStack.frontend.map((t: string) => colors.highlight(t)).join(', ')}`);
    }

    if (techStack.backend.length > 0) {
      sections.push(`${colors.primary('Backend:')} ${techStack.backend.map((t: string) => colors.highlight(t)).join(', ')}`);
    }

    if (techStack.database.length > 0) {
      sections.push(`${colors.primary('Database:')} ${techStack.database.map((t: string) => colors.highlight(t)).join(', ')}`);
    }

    if (techStack.testing.length > 0) {
      sections.push(`${colors.primary('Testing:')} ${techStack.testing.map((t: string) => colors.highlight(t)).join(', ')}`);
    }

    if (techStack.devTools.length > 0) {
      sections.push(`${colors.primary('Dev Tools:')} ${techStack.devTools.map((t: string) => colors.highlight(t)).join(', ')}`);
    }

    const content = sections.length > 0 ? sections.join('\n') : colors.dim('Basic technology stack detected');

    return `\n${colors.heading('🛠️  Technology Stack')}\n\n${content}`;
  }

  /**
   * Format complexity analysis section
   */
  private static formatComplexity(complexity: any): string {
    const levelColors: Record<string, (text: string) => string> = {
      'Simple': colors.success,
      'Moderate': colors.warning,
      'Complex': colors.warning,
      'Enterprise': colors.error,
    };
    const levelColor = levelColors[complexity.level] || colors.neutral;

    const maintainabilityColors: Record<string, (text: string) => string> = {
      'Excellent': colors.success,
      'Good': colors.success,
      'Fair': colors.warning,
      'Poor': colors.error,
    };
    const maintainabilityColor = maintainabilityColors[complexity.maintainability] || colors.neutral;

    const content = `
${colors.primary('Complexity Level:')} ${levelColor(complexity.level)} ${colors.dim(`(Score: ${complexity.score}/10)`)}
${colors.primary('Maintainability:')} ${maintainabilityColor(complexity.maintainability)}

${colors.primary('Project Metrics:')}
  • ${colors.dim('Dependencies:')} ${colors.highlight(complexity.factors.dependencies.toString())}
  • ${colors.dim('Dev Dependencies:')} ${colors.highlight(complexity.factors.devDependencies.toString())}
  • ${colors.dim('Lines of Code:')} ${colors.highlight(complexity.factors.linesOfCode.toLocaleString())}
  • ${colors.dim('File Count:')} ${colors.highlight(complexity.factors.fileCount.toString())}
`;

    return `\n${colors.heading('📈 Complexity Analysis')}\n${content}`;
  }

  /**
   * Format recommendations section
   */
  private static formatRecommendations(recommendations: Recommendation[]): string {
    if (recommendations.length === 0) {
      return `\n${colors.heading('💡 Recommendations')}\n${colors.success('✓ Project follows best practices - no immediate recommendations')}`;
    }

    let section = `\n${colors.heading('💡 Improvement Recommendations')}\n`;

    recommendations.forEach((rec, index) => {
      const priorityColor = {
        'High': colors.error,
        'Medium': colors.warning,
        'Low': colors.dim,
      }[rec.priority] || colors.neutral;

      const recContent = `
${colors.primary(rec.title)} ${priorityColor(`[${rec.priority} Priority]`)}
${colors.dim(rec.description)}

${colors.primary('Action:')} ${rec.action}
${colors.primary('Impact:')} ${colors.success(rec.impact)}
`;

      section += boxes.box(recContent.trim(), {
        title: `${rec.category} Recommendation`,
        borderColor: priorityColor,
        padding: 1,
      }) + '\n';
    });

    return section;
  }

  /**
   * Format report footer
   */
  private static formatFooter(): string {
    return `
${colors.heading('🚀 Next Steps with PromptBrain')}

Now that your project is analyzed, you can:
  ${colors.dim('1.')} ${colors.highlight('pb enhance "prompt"')} - Get context-aware enhancements
  ${colors.dim('2.')} ${colors.highlight('pb devsync')} - Sync your current development context
  ${colors.dim('3.')} ${colors.highlight('pb link notion')} - Connect external tools for richer context

${colors.dim('This analysis helps PromptBrain provide more relevant suggestions for your specific project.')}
`;
  }

  /**
   * Format a quick summary for display during init
   */
  static formatQuickSummary(report: ProjectReport): string {
    const { basicInfo, purpose, complexity } = report;
    
    return boxes.box(`
${colors.primary('Project:')} ${colors.highlight(basicInfo.name)}
${colors.primary('Domain:')} ${colors.highlight(purpose.domain)}
${colors.primary('Type:')} ${colors.highlight(purpose.category)}
${colors.primary('Complexity:')} ${colors.highlight(complexity.level)}
${colors.primary('Features:')} ${purpose.features.slice(0, 3).join(', ')}
`, {
      title: 'Project Analysis Summary',
      borderColor: colors.success,
      padding: 1,
    });
  }
}

export default ReportFormatter;